[project]
name = "sortit"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "django>=5.2.8",
  "django-stubs>=5.2.7",
  "gunicorn>=23",
  "pillow>=12",
  "whitenoise>=6.12.0",
]

[tool.djlint]
indent = 2
format_js = true
format_css = true
line_break_after_multiline_tag = true
css.indent_size = 2
js.indent_size = 2

[tool.pyright]
typeCheckingMode = "basic"
