# Generated by Django 6.0.6 on 2026-08-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sha256',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
    ]
