# Generated by Django 5.2.7 on 2025-11-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='label',
            name='imageset',
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, default=None, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
