# Generated by Django 5.2.8 on 2025-11-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0002_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filepath',
            field=models.FilePathField(),
        ),
    ]
