# Generated by Django 5.2.7 on 2025-11-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0002_rename_name_label_label_remove_label_imageset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='labels',
            field=models.ManyToManyField(to='sortIT.label'),
        ),
    ]
