# Generated by Django 6.0.6 on 2026-08-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0002_image_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='label_imsize',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
