# Generated by Django 6.0.6 on 2026-08-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0003_userpreferences_label_imsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='imsize',
            new_name='sort_imsize',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='nimgs',
            new_name='sort_nimgs',
        ),
    ]
