# Generated by Django 5.2.7 on 2025-11-12 18:55

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0003_imageset_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='label',
        ),
        migrations.AddField(
            model_name='annotation',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageset',
            name='timespent',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='sortIT.image'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='desc',
            field=models.TextField(blank=True, default=None, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='labels',
            field=models.ManyToManyField(related_name='imagesets', to='sortIT.label'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sortIT.project'),
            preserve_default=False,
        ),
    ]
