# Generated by Django 6.0.6 on 2026-08-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0004_rename_imsize_userpreferences_sort_imsize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
