# Generated by Django 5.2.7 on 2025-11-12 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0004_remove_image_label_annotation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sortIT.label'),
        ),
    ]
