# Generated by Django 6.0.6 on 2026-08-26 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0005_userpreferences_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
