# Generated by Django 5.2.7 on 2025-11-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0005_alter_annotation_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='label',
            new_name='name',
        ),
    ]
