# Generated by Django 5.2.7 on 2025-11-12 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0006_rename_label_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageset',
            field=models.ManyToManyField(related_name='image', to='sortIT.imageset'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='labels',
            field=models.ManyToManyField(related_name='imageset', to='sortIT.label'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageset', to='sortIT.project'),
        ),
    ]
