# Generated by Django 6.0.6 on 2026-08-27 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0006_alter_annotation_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='annotation',
            name='unique_user_image_label',
        ),
        migrations.RemoveConstraint(
            model_name='annotation',
            name='unique_user_image_null_label',
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(fields=('user', 'image', 'imageset', 'label'), name='unique_user_image_imageset_label'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(condition=models.Q(('label__isnull', True)), fields=('user', 'image', 'imageset'), name='unique_user_image_imageset_null_label'),
        ),
    ]
