# Generated by Django 5.2.7 on 2025-11-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0007_alter_image_imageset_alter_imageset_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageset',
            field=models.ManyToManyField(related_name='images', to='sortIT.imageset'),
        ),
    ]
