# Generated by Django 5.2.7 on 2025-11-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortIT', '0008_alter_image_imageset'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sortIT.project'),
            preserve_default=False,
        ),
    ]
